### ISSUE TITLE
Video player

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1294]
I vote to add video player codes on pi , we can use player on some modules , 

At this moment I use jwplayer 5 on my modules but its old version. 

I think we can use one of this players : 
* jwplayer 6 : http://www.jwplayer.com/ support video and audio , not opensurece and licence needed
* videojs : http://www.videojs.com/ just support video and its open source and no licence needed
* jplaye : http://jplayer.org/ support video and audio and its open source and no licence needed

But for video , I think videojs is better than jplaye !  

For video , html5 video / audio  tags support MP4 by h264 encode for video and  AAC or MP3 for audio 

More info : https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

**Comment by Marc-pi** [comment]
you will find here a comparison table with all html5 players
http://praegnanz.de/html5video/

they tag those as most stable / most popular (integration available for CMS)
* flowplayer (WP ) jQuery GPL but limited https://flowplayer.org/pricing/
* JWplayer (WP, drupal) commercial license http://www.jwplayer.com/pricing/ ==> used by TripAdvisor, The Wahsington Post
* mediaelements.js (WP core, drupal) jQuery https://github.com/johndyer/mediaelement/ MIT License
* SublimeVideo (WP) seem not opensource
* VideoJs (WP, Joomla, Drupal) https://github.com/videojs/video.js  Apache license ==> used by Vine and AirBnB

We could also have considered 2 others
* Projekktor GPL https://github.com/frankyghost/projekktor (non jQuery) Audio+Video
* Yendifplayer (WP, Joomla) GPL jQuery http://yendifplayer.com/quick-start-guide.html, but to remove logo there is a commercial license

They've list also
* jplayer : https://github.com/happyworm/jPlayer (used by BBC & Aljazzera) JQuery, GPL

=> i would shortlist because opensource and being on github
* VideoJs http://www.videojs.com/ jQuery  Video (Audio through plugin)
* mediaelements.js (wordpress core) http://mediaelementjs.com/ jQuery Video+Audio
* Projekktor GPL https://github.com/frankyghost/projekktor (non jQuery) Audio+Video
* jplayer : https://github.com/happyworm/jPlayer (used by BBC & Aljazzera) JQuery, GPL Audio+Video

> To choose, we need IMHO to check, ahead of OpenSource License and being on GitHub

* Responsiveness, 
* accepted Video/Audio Encoding vs Browser compat
* community engagement : active?
* popularity

**Comment by Marc-pi** [comment]
==> seems we can go with videojs...

**Comment by voltan** [comment]
I agree whit videojs , 

can I send pull request for it? and which folder is good for put files ? @taiwen

**Comment by taiwen** [comment]
- Add `Videojs.php` to `lib/Pi/View/Helper/`
- Put '/video-js/' in `www/static/`

**Comment by voltan** [comment]
Added
